# Assignment 01 - Python, NumPy, Matplotlib and Pandas

**Due: Fri 09/04/2020**


**Please fill these in before submitting, just in case I accidentally mix up file names while grading**:

Name: Joe Student

CWID-5: (Last 5 digits of cwid)

In [ ]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

## Problem 1: Python Functions, Recursion and Memoization
----

Memoization is a technique that uses a dictionary to cache computed results.
Mamoization can result in significant speed improvements for some recursive and other
types of algorithms that need a subcalculation repeated many times.

For example, an inefficient implementation of calculating the $n^{th}$
[Fibonacci number](https://en.wikipedia.org/wiki/Fibonacci_number)
might look like the following.  Do you understand why this implementation
is inefficient? It performs many redundant recursive calls, try creating a tree of
the calls for `fib(5)` that are done.  These redundant calculations quickly
(exponentially) explode the amount of work that is performed by this naive 
implementation.

In [ ]:
def fibonacci_inefficient(n):
    """Calculate the nth Fibonacci number of the Fibonacci sequence using
    recursion.  The base cases of the sequence are defined as:
    
    fib(1) = 1
    fib(2) = 2
    
    And the recursive case is that
    
    fib(n) = fib(n - 1) + fib(n - 2)
    
    Paramters
    ---------
    n - We are to calculate the nth number of the Fibonacci sequence and return it.
    
    Returns
    -------
    fib(n) - Returns the calculated nth Fibonacci number of the Fibonacci sequence.
    """
    if n == 1:
        return 1
    elif n == 2:
        return 2
    else:
        return fibonacci_inefficient(n - 1) + fibonacci_inefficient(n - 2)

In [ ]:
# base cases
print(fibonacci_inefficient(1))
print(fibonacci_inefficient(2))

# try 3 and 4
print(fibonacci_inefficient(3))
print(fibonacci_inefficient(4))

# try 10, should have an answer of 89
print(fibonacci_inefficient(10))

In [ ]:
# correct answer is 39088169
fibonacci_inefficient(37)

In [ ]:
# notice the time it takes because of all of the repeated, inefficient work
# I normally see over 6 seconds on average to calculate the 37th Fibonacci
# number
%timeit fibonacci_inefficient(37)

Write an efficient version of calculating the $n^{th}$ Fibonacci number using
the memoization technique.  Your function should take 2 parameters, `n`
the Fibonacci number to calculate, and `d` a dictionary.  You should use
a default value for your dictionary, and initialize it for the base
cases of `fibonacci_efficient(1) = 1` and `fibonacci_efficient(2) = 2`.
The signature of the function you should write should look like this:

```python
def fibonacci_efficient(n, d = {1:1, 2:2}):
    """Calculate the nth Fibonacci number of the Fibonacci sequence using
    recursion and memoization.  The base cases of the sequence are
    defined as:
    
    fib(1) = 1
    fib(2) = 2
    
    And the recursive case is that
    
    fib(n) = fib(n - 1) + fib(n - 2)
    
    Paramters
    ---------
    n - We are to calculate the nth number of the Fibonacci sequence and
        return it.
    d - A dictionary of cached previously computed results.  By default, the
        base cases of fib(1) = 1 and fib(2) = 2 are initialized for the
        dictionary, so that the first call to this function can be simply
        done as:
             fibonacci_efficient(10)
             
    Returns
    -------
    fib(n) - Returns the calculated nth Fibonacci number of the 
        Fibonacci sequence.
    """
```


Wrte your implementation and demonstrate the time of your implementation to calculate
the $37^{th}$ Fibonacci number as we did above.  If you implement the memoization
correctly, you will find that your function only takes 100s of nano seconds, 
which is almost billion times speed improvement.

In [ ]:
# write your implementation of fibonacci_efficient here
# do not remove the function docstring, always include or create a docstring for all 
# non-trival functions you write for assignments for this class

In [ ]:
# base cases, might want to test your version still works for the base cases

In [ ]:
# demonstrate that your implementation is almost 1 billion times faster here using %timeit

## Problem 2: NumPy Operations
----



Create the specified NumPy arrays using NumPy library and/or vectorized operations (do not use any
loops in your following answers).

Create an array named `x` with 5 values linearly spaced from -2.0 to 2.0.  Reshape x to be a row
matrix with 1 row and 5 columns.  Your result should look like this:

```python
>>> print(x)
[[-2. -1.  0.  1.  2.]]
```

In [ ]:
# create x here

Create an array named `y` with 4 values linearly spaces from -1 to 1.  Reshape y to be
a column matrix with 1 column and 4 rows.  `y` should look like this when done:

```python
>>> print(y)
[[-1.        ]
 [-0.33333333]
 [ 0.33333333]
 [ 1.        ]]
```

In [ ]:
# create y here

The `np.tile()` function can be used to repeat parts of an array.  For example, we can turn
`x` into a 4 rows by 5 columns matrix, repeating its row, like this (this assumes you defined
`x` correctly in the previous cells):

```python
>>> X = np.tile(x, (rows,1))
>>> print(X)
[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]

>>> print(X.shape)
(4, 5)
```

In [ ]:
# If you defined small x correctly above, you can create the matrix big X here by uncommenting the following
# X = np.tile(x, (rows,1))
# print(X)
# print(X.shape)

In the next cell demonstrate tiling the `y` column array to also be of shape `(4,5)`, but where each
column is a repeatition of the current single column in `y`.

In [ ]:
# tile y's column to end up with 5 repeated columns of y, and a shape again of (4,5)

Now demonstrate the result of doing a vectorized multiplication of the tiled result of `y` times
the complex number 0 + 1j.  The result should look like this.  Notice that the original contents
of `y` are multiplied times both the real and complex part, but since the real part is 0 you end up
only with the complex part.

```python
>>> print(Y)
array([[-0.-1.j        , -0.-1.j        , -0.-1.j        ,
        -0.-1.j        , -0.-1.j        ],
       [-0.-0.33333333j, -0.-0.33333333j, -0.-0.33333333j,
        -0.-0.33333333j, -0.-0.33333333j],
       [ 0.+0.33333333j,  0.+0.33333333j,  0.+0.33333333j,
         0.+0.33333333j,  0.+0.33333333j],
       [ 0.+1.j        ,  0.+1.j        ,  0.+1.j        ,
         0.+1.j        ,  0.+1.j        ]])

>>> print(Y.shape)
(4, 5)
```

In [ ]:
# perform vectorized multiplication of matrix and the complex number here

Using the previous 2 tile commands and vectorized multiplication, create a new matrix Z that is
of shape `(4,5)`.  Z is the result of adding up the tiled of `x` and `y * 1j`.

You should get the following result.  Notice that `Z` the real part is the part from the tiled `x`
and the imaginary part comes from the tiled `y`:

```python
>>> print(Z)
[[-2.-1.j         -1.-1.j          0.-1.j          1.-1.j
   2.-1.j        ]
 [-2.-0.33333333j -1.-0.33333333j  0.-0.33333333j  1.-0.33333333j
   2.-0.33333333j]
 [-2.+0.33333333j -1.+0.33333333j  0.+0.33333333j  1.+0.33333333j
   2.+0.33333333j]
 [-2.+1.j         -1.+1.j          0.+1.j          1.+1.j
   2.+1.j        ]]
>>> print(Z.shape)
(4, 5)
```

In [ ]:
# perform vectorized addition and create new array Z here

In the next cell, create an array called `T` which will be used to record time stamps later on.
`T` should be the same shape as Z `(4, 5)` but filled all with 0's.

In [ ]:
# Create an array called T of the same shape as Z of all zeros

Now create an array named `M` which will be used as a mask later on.  `M` should be the same shape
as `Z`, but its values should be of `dtype=bool` and all of the boolean values should initially
be set to `True`.  You should get the following results for this array named `M`:

```python
>>> print(M)
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]

>>> print(M.shape)
(4, 5)

>>> print(M.dtype)
bool
```

In [ ]:
# create an array called M of the same size as Z but using dtype=bool and initially all values
# are set to True

Now create an array called `C` of complex values.  `C` should be the same shape as `Z` and it should
be filled with the complex value `-0.4 + 0.6j` for all elements.

```python
>>> print(C)
[[-0.4+0.6j -0.4+0.6j -0.4+0.6j -0.4+0.6j -0.4+0.6j]
 [-0.4+0.6j -0.4+0.6j -0.4+0.6j -0.4+0.6j -0.4+0.6j]
 [-0.4+0.6j -0.4+0.6j -0.4+0.6j -0.4+0.6j -0.4+0.6j]
 [-0.4+0.6j -0.4+0.6j -0.4+0.6j -0.4+0.6j -0.4+0.6j]]

>>> print(C.shape)
(4, 5)

>>> print(C.dtype)
complex128
```

In [ ]:
# create an array called C of the same shape as Z, but all filled with the complex value
# -0.4 + 0.6j

The `np.abs()` function is a vectorized NumPy function that will compute the absolute value of an
array of values.  However, the 
[absolute value of a complex number](https://en.wikipedia.org/wiki/Absolute_value#Complex_numbers)
is defined asa function of the real and imaginary parts.  For example, try finding the
absolute value of your `Z` matrix, you should get the following result:

```python
>>> np.abs(Z)
array([[2.23606798, 1.41421356, 1.        , 1.41421356, 2.23606798],
       [2.02758751, 1.05409255, 0.33333333, 1.05409255, 2.02758751],
       [2.02758751, 1.05409255, 0.33333333, 1.05409255, 2.02758751],
       [2.23606798, 1.41421356, 1.        , 1.41421356, 2.23606798]])
```

In [ ]:
# calculate the absolute value of Z here, you should get the same result shown in previous cell
# np.abs(Z)

Perform the following vectorized calculations in this order.

1. Create a mask array named `M` that is the same shape as `Z` and is `False` at all locations
where the absolute value of `Z` is greater than 2.
2. Update `T` to be 1 for all places where the mask `M` is true
3. Update `Z` but only for the values where the mask `M` is true. Update it using the following 
quadratic formula
$$
Z = Z^2 + C
$$
This is a vectorized operation, but again only perform this update of `Z` for those values where the
mask `M` is true (**HINT**: using boolean indexing).

The result will be `(4,5)` shaped matrices in all cases, and you should get the following for
`M`, `T` and `Z` if you perform the vectorized operations correctly:

```python
>>> print(M)
[[False  True  True  True False]
 [False  True  True  True False]
 [False  True  True  True False]
 [False  True  True  True False]]

>>> print(T)
[[0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]]

>>> print(Z)
[[-2.        -1.j         -0.4       +2.6j        -1.4       +0.6j
  -0.4       -1.4j         2.        -1.j        ]
 [-2.        -0.33333333j  0.48888889+1.26666667j -0.51111111+0.6j
   0.48888889-0.06666667j  2.        -0.33333333j]
 [-2.        +0.33333333j  0.48888889-0.06666667j -0.51111111+0.6j
   0.48888889+1.26666667j  2.        +0.33333333j]
 [-2.        +1.j         -0.4       -1.4j        -1.4       +0.6j
  -0.4       +2.6j         2.        +1.j        ]]

```


In [ ]:
# create the mask matrix M here as described


In [ ]:
# Update the T matrix here as described


In [ ]:
# using M as a mask, computer Z**2 + C and put the value back into Z
# Make sure you get the same result shown above, and that you are only computing the updated
# values of Z that True in the mask M

## Problem 3: Vectorized Functions and Plotting
----

Using the operations to create and update `Z` in the previous problem, we will now write a function
that will perform the update on `Z`, `T`, and `M` repeatedly.  The formula to update `Z` we just
did is the quadratic polynomial used to calculate *Julia Sets*.  Given a matrix of complex numbers,
if you successively iterate the updates of `Z` you will get this set.

Create a function named `iterate_julia_set`.  This function will have the following signature:

```python
def iterate_julia_set(Z, num_iters=256, c=-0.4+0.6j):
    """Iterate the array of complex numbers Z a number of times, updating them using the 
    quadratic polynomial to calculate the Julia set and Julia fractals.
    
    Parameters
    ----------
    Z - A 2d NumPy array of complex numbers.  Should be a tiled grid of real+complex parts 
        linearly spaces over some area we want to calculate the julia set for.
    c - A complex number, the constant to be added to each value on each iteration for numbers
        still in the julia set.  Defaults to c=-0.4+0.6j
    num_iters - Number of iterations/updates to perform of the Z, M and T matrices.
        Defaults to performing 256 iterations
        
    Returns
    -------
    T - Returns a NumPy array of the same shape as the input Z. T contains the time step/stamp
        of when each point in Z fell out of the julia set during iterations.
    """

```

Your function should do the following.

1. Make a copy of the `Z` array that is passed in, so that if we update it the updates are not seen
outside of the function.
2. Initialize `C`, `M` and `T` based on the shape of `Z`, as you did for the previous question.  `T` is 
an array of time stamps, that are all initially 0.  `C` is simply an array of complex numbers, you
should use the parameter `c` as the initial value for all values in `C`.  And `M` is a boolean
mask that keeps track of which points in `Z` have an absolute value above or below the threshold
of 2.
3. Then create a loop that iterats the indicated `num_iters` times.  Insice of your loop 
you should perform the 3 updates we did previously.  `Z` is updated as `Z^2 + c` but only for
the values where the mask `M` is true.  Then the mask `M` is updated since the values of
`Z` have now changed.  And finally, mark any values in `T` using the mask with the current
timestamp, only for those locations where the mask `M` is `True`.

At the end you should return the resulting time stamps array `T` as the result from your
function.

Write your implementation of the function in the next cell.  Don't forget to include the function
doc string documentation, which you should have for all functions you write for all assignments for this
class.

In [ ]:
# write your implementation of the iterate_julia_set function here.
# Make sure you include the function docstring documentation of the function.  You must always have
# function docstring documentation for all of your funcitons for these assignments.


If you implement your function correctly, then the result of running the following 3
cells should be a figure/image plot of the julia fractal set.  If your implementation is correct,
then the figure will look like the image shown here, using a default of `c=-0.4+0.6j` for the
complex number constant and 256 iterations in total.

![title](../figures/assg-01-problem-03-result.png)

In [ ]:
# This cell create a new Z of complex numbers on a grid, similar to but bigger than the example you
# created previously

# dimensions grid points we will generate for our Z matrix of complex numbers to iterate
# (actually 1/2 the dimensions, since we go from -cols to +cols and -rows to +rows)
cols = 480
rows = 320

# figure scale
scale = 300

# create Z matrix of points, we start simply with a set of linearly
# spaced points representating the range and grid for the x and y axis.
# Then we can use the tile() funciton to create a grid
x = np.linspace(-cols / scale, cols / scale, num=cols).reshape(1, cols)
y = np.linspace(-rows / scale, rows / scale, num=rows).reshape(rows, 1)
Z = np.tile(x, (rows, 1)) + 1j * np.tile(y, (1, cols))

In [ ]:
# this cell calls your function, your function should work without changing anything in this
# cell (e.g. the signature and return result must be as shown here)

num_iter = 256
c = -0.4 + 0.6j
N = iterate_julia_set(Z, num_iter, c)

In [ ]:
# this cell plots the julia set fractal computed by your function

fig = plt.figure(figsize=(10,8))
ax = fig.add_axes([0, 0, 1, 1], frameon=False, aspect=1)
ax.set_xticks([])
ax.set_yticks([])

plt.imshow(np.flipud(N), cmap='hot');
title = r'Julia set for $c = %s$ %d iterations' % (c, num_iter)
plt.title(title, fontsize=20);
#plt.savefig('../figures/assg-01-problem-03-result.png');

## Problem 4: Pandas
----

There is a file in your repository assignments directory, under the data subdirectory,
called `assg-01-data.csv` formatted using comma separated values.  This file
contains 15 lines of sales data.  Read the data into a `Pandas` data frame simply named `d`, and display the 
first 5 lines of data using the `head()`
member function.  Display the last 5 lines of the data using the `tail()` member function.

In [ ]:
# load the assg-01-data.csv file into a Pandas data frame

In [ ]:
# display the first 5 samples from the data frame

In [ ]:
# display the last 5 samples from the data frame

As you should be able to see, the data consists of some customer sales' information, along with the customer address.  
The data contains sales information for 3 months.

In the next cell, create a new column in your `Pandas` data frame named `total`.  This column should contain the total
sales for each row for the 3 months of data present.

In [ ]:
# create a new column which is the total for each account of their Jan, Feb and Mar sales


Using pandas data frame operations only, find out the following information:

- The total sum of sales in the month of Jan
- The minimum sales amount in the month of Feb
- The average (mean) sales for the month of Mar
- Change the name of the column from `postal-code` to `zipcode`.  Having a - in the name makes it
unusable as an attribute name, so we might want to fix this.
- Count the total number of missing items in the state and postal-code attributes

In [ ]:
# total sum of sales in the month of Jan

In [ ]:
# minum sales amount in the month of Feb

In [ ]:
# average sales for month of Mar

In [ ]:
# change the name from postal-code to zipcode here


In [ ]:
# number of missing items in state


In [ ]:
# number of missing items in zipcode


Finally plot the Jan, Feb, Mar and total sales data as bar plots using the `plot()` convenience function
available from a Pandas `DataFrame`.

Label your x and y axis on your plot.  Also change the x tick labels to be the account numbers instead
of 0,1,2,...14.  Also give the plot an appropriate title.  You will need to use matplotlib 
functions after you create your bar chart to add the labels and change the tic marks.

In [ ]:
# create your bar chart here using plot() function of data frame
# also tweak the plot to add x and y labels, a title, and label the xticks as described


**Extra Credit**: Perhaps we would like to have our visualization sorted
by the total sales.  Replot the bar plot but sort the account numbers by their
total sales, so we can more easily see the accounts from the lowest sales to our
highest sales.